project_name: lgtv-sdp

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: freebsd
        goarch: mips
      - goos: freebsd
        goarch: mipsle
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  - replacements:
      darwin: macos
      386: i386
      amd64: x86_64
    wrap_in_directory: "lgtv-sdp"
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
